import pandas as pd
import datetime

def get_timestamp():
    #create timestamp for loggin and uniquely naming output files
    now = datetime.datetime.now()
    current_time_stamp = f'{now.year}'
    current_time_stamp += f'{now.year}'
    current_time_stamp += f'{now.month}'
    current_time_stamp += f'{now.day}'
    current_time_stamp += f'{now.second}'
    current_time_stamp += f'{now.microsecond}'
    return(current_time_stamp)
 

neighborhoods =  set([
 'Alamo Square',
 'Anza Vista',
 'Apparel City',
 'Aquatic Park / Ft. Mason',
 'Ashbury Heights',
 'Balboa Terrace',
 'Bayview',
 'Bayview Hunters Point',
 'Bernal Heights',
 'Bret Harte',
 'Buena Vista',
 'Candlestick Point SRA',
 'Castro',
 'Castro/Upper Market',
 'Cathedral Hill',
 'Cayuga',
 'Central Waterfront',
 'Chinatown',
 'Civic Center',
 'Clarendon Heights',
 'Cole Valley',
 'Corona Heights',
 'Cow Hollow',
 'Crocker Amazon',
 'Diamond Heights',
 'Dogpatch',
 'Dolores Heights',
 'Downtown / Union Square',
 'Duboce Triangle',
 'Eureka Valley',
 'Excelsior',
 'Fairmount',
 'Financial District',
 'Financial District/South Beach',
 'Fishermans Wharf',
 'Forest Hill',
 'Forest Knolls',
 'Glen Park',
 'Golden Gate Heights',
 'Golden Gate Park',
 'Haight Ashbury',
 'Hayes Valley',
 'Holly Park',
 'Hunters Point',
 'India Basin',
 'Ingleside',
 'Ingleside Terraces',
 'Inner Richmond',
 'Inner Sunset',
 'Japantown',
 'Laguna Honda',
 'Lake Street',
 'Lakeshore',
 'Laurel Heights / Jordan Park',
 'Lincoln Park',
 'Lincoln Park / Ft. Miley',
 'Little Hollywood',
 'Lone Mountain',
 'Lone Mountain/USF',
 'Lower Haight',
 'Lower Nob Hill',
 'Lower Pacific Heights',
 'Marina',
 'McLaren Park',
 'Merced Heights',
 'Merced Manor',
 'Midtown Terrace',
 'Mint Hill',
 'Miraloma Park',
 'Mission',
 'Mission Bay',
 'Mission Dolores',
 'Mission Terrace',
 'Monterey Heights',
 'Mt. Davidson Manor',
 'Nob Hill',
 'Noe Valley',
 'North Beach',
 'Northern Waterfront',
 'Oceanview',
 'Oceanview/Merced/Ingleside',
 'Outer Mission',
 'Outer Richmond',
 'Outer Sunset',
 'Pacific Heights',
 'Panhandle',
 'Parkmerced',
 'Parkside',
 'Parnassus Heights',
 'Peralta Heights',
 'Polk Gulch',
 'Portola',
 'Potrero Hill',
 'Presidio',
 'Presidio Heights',
 'Presidio National Park',
 'Presidio Terrace',
 'Produce Market',
 'Rincon Hill',
 'Russian Hill',
 'Seacliff',
 'Sherwood Forest',
 'Showplace Square',
 'Silver Terrace',
 'South Beach',
 'South of Market',
 'St. Francis Wood',
 'St. Marys Park',
 'Stonestown',
 'Sunnydale',
 'Sunnyside',
 'Sunset/Parkside',
 'Sutro Heights',
 'Telegraph Hill',
 'Tenderloin',
 'Treasure Island',
 'Twin Peaks',
 'Union Street',
 'University Mound',
 'Upper Market',
 'Visitacion Valley',
 'West Portal',
 'West of Twin Peaks',
 'Western Addition',
 'Westwood Highlands',
 'Westwood Park',
 'Yerba Buena Island'])
